### ISSUE TITLE
Prettify front-end

### ISSUE THREAD

**Issue by athityakumar** [metakgp/naarad#13]
Front-end could probably use a `card-panel` for each post. Also, we can include a `mfqp` sort-of search bar too.

**Comment by hargup** [comment]
`mfqp` like search will be really cool.

**Comment by vivekiitkgp** [comment]
@athityakumar Would you like to try this? We already have the JSON feed so see if the search can work directly out of the box using the post content?

**Comment by athityakumar** [comment]
I've added PR #16 and #15 to improve front-end.

I'll start working on the search soon...

**Comment by athityakumar** [comment]
Front-end has been prettified, and `mfqp-like search` has integrated! So, this issue deserves to be closed right away... :smile:
