### ISSUE TITLE
Shared posts are showing nothing

### ISSUE THREAD

**Issue by DefCon-007** [metakgp/naarad#18]
<img width="1117" alt="screen shot 2016-08-19 at 7 20 43 pm" src="https://cloud.githubusercontent.com/assets/16754547/17811833/2116e96c-6642-11e6-860a-4be30bb931e2.png">
If a page shares another page's post then it is showing nothing. Attached is the screenshot of the post on naarad and below is the post URL. 
https://www.facebook.com/156819310131_10154281614800132

**Comment by athityakumar** [comment]
Even events are not shown, like this post of Awaaz.

![image](https://cloud.githubusercontent.com/assets/17109060/17812448/beaff3ba-6644-11e6-9ac5-7253ed922012.png)
Link to post : https://www.facebook.com/events/113540679091325/

**Comment by vivekiitkgp** [comment]
It's possible that the information is contained in some other `field` of the query. One might have to explore from the Facebook's Graph API.

**Comment by DefCon-007** [comment]
I will do it tonight.
