### ISSUE TITLE
Add a footer showing information linking to metakgp

### ISSUE THREAD

**Issue by hargup** [metakgp/naarad#19]
We should have a footer linking to the source and metakgp wiki.

**Comment by athityakumar** [comment]
A sticky footer or a footer at the very bottom that shows up when you scroll till the end?

The latter is useless IMO, as none has the time / patience to cross the numerous posts & hence it becomes redundant.

If it's the former, wouldn't it be a bit like Youtube ads? Viewers want to watch more of the feed, while a sticky footer comes & blocks a (negligible?) part of their feed!

Maybe we can start with a short paragraph after "NAARAD" title with the info, and then start displaying the feed?

**Comment by vivekiitkgp** [comment]
I'd prefer something very simple like:
```
----- Naarad ------
         by Metakgp
```
Where the top line is as it's now. Just another line below it with smaller text mentioning Metakgp and linking to Facebook or Wiki page. Naarad can also link to its page on Wiki.

**Comment by athityakumar** [comment]
@vivekiitkgp @hargup : Added a sticky header and metakgp links with search in the header... Can you review the present naarad?

**Comment by vivekiitkgp** [comment]
Looks great! Thanks!
