### ISSUE TITLE
Account deletion

### ISSUE THREAD

**Issue by Sarmada2809** [metakgp/naarad#22]
After an account is deleted,again to signup with the same email it is not allowing to do it.It is showing user is registered and redirectimg to login page even the account is deleted.we tried even to login with the previous credentials but its showing invalid user or password

**Comment by proffapt** [comment]
Hi @Sarmada2809,

Thanks for the bug report. Can you share your institute email, so that we can further have a look into it?

**Comment by Sarmada2809** [comment]
***@***.***

**Comment by proffapt** [comment]
umm, I can't see the email..

**Comment by proffapt** [comment]
I don't see your username, users with insufficient perms were deleted, if 
- `sreejanyareddy` was your username then follow the sign-up process again
- Update shall be pushed soon, disabling the feature.
