### ISSUE TITLE
[BUG] Files route isn't protected by heimdall

### ISSUE THREAD

**Issue by proffapt** [metakgp/naarad#23]
Following behaviour is observed.

### Conditions

- Heimdall auth not performed (no heimdall token present)
- Two URls
  - Valid attachment URL (A)
  - In-valid attachment URL (B)

### Behaviour

- A: Able to download, not protected by heimdall
- B: Heimdall appears, protected by heimdall

**Comment by Bikram-ghuku** [comment]
Can I work on this?

**Comment by proffapt** [comment]
Sure, assigning you this. Keep us updated about this issue.

**Comment by proffapt** [comment]
@Bikram-ghuku updates?

**Comment by Bikram-ghuku** [comment]
Was A bit busy today, looking into it asap

**Comment by proffapt** [comment]
@Bikram-ghuku updates?

**Comment by proffapt** [comment]
@Bikram-ghuku ?

**Comment by Bikram-ghuku** [comment]
Still tyring to figure out what is causing the bug.....

**Comment by Bikram-ghuku** [comment]
I have not found any solution to this bug.  I am  unassigning myself. This issue is open to be taken up.

**Comment by proffapt** [comment]
It works now, somehow :looksaway:
