### ISSUE TITLE
Support for mobile screens

### ISSUE THREAD

**Issue by athityakumar** [metakgp/naarad#25]
The existing web-scripts are meant to be very friendly to be viewed in any screen... However, some posts have the website links that are too huge without a gap (like `http://newsroom.ucla.edu/releases/11-million-gift-establishes-mani-l-bhaumik-institute-for-theoretical-physics-at-ucla` of ScholsAve from post : https://www.facebook.com/scholarsavenue/posts/10154204012475132).

So, it'd be better if we could handle them as hyperlinks while displaying - like rather than displaying the url, we can show "Link" with a hyperlink to the respective links.

Probably a method should be written in `fbscraper.py` to store them as `hyperlinks` field in `feed.json` and then they should be removed from the `message` field of `feed.json` too.

**Comment by athityakumar** [comment]
@DefCon-007 : Can you work on this?

**Comment by vivekiitkgp** [comment]
I think #3 will take care of this. That's a better feature to work on. :)
