### ISSUE TITLE
Too many requests (429) error for naarad-api backend

### ISSUE THREAD

**Issue by proffapt** [metakgp/naarad#25]

**Comment by dhanvithnayak** [comment]
Shall I work on this?

**Comment by proffapt** [comment]
go ahead, and keep me updated by yourself.

**Comment by proffapt** [comment]
@BAGUVIX456 updates?

**Comment by dhanvithnayak** [comment]
Working on it, still not able to pinpoint what exactly is causing the error

**Comment by proffapt** [comment]
The rate limiting is occurring on `/request` endpoint not on all of the `naarad-api` backend. That is the 429 is coming from naarad backend not our backend.

**Comment by proffapt** [comment]
https://github.com/metakgp/naarad/commit/9cc6c19b28741dddae7c611c3de10c2c61844134

Should fix it, let's check in coming 3-4 days how it performs.

**Comment by proffapt** [comment]
Update: Didn't fix.

**Comment by proffapt** [comment]
So the probable reason behind this behaviour is following:
<img width="745" alt="image" src="https://github.com/user-attachments/assets/4166a3a0-188e-40e0-a80b-0ed77f537e7d">

Observe that both the usernames have the same public ip. And the limits are applied to these ip addresses. This is because KGP has handful of public ips, resulting in rate-limiting affecting not just a single user but a collection of users.

So, as fix, following is implemented until a better fix is ideated:
- Rate limiting stays the same, need for DDoS protection
- Restart the service every 6hrs using a cronjob, to keep the service always running at any case
