### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by SRSSOUMYA** [metakgp/naarad#26]
Add forgot password and reset password feature in login page

**Comment by proffapt** [comment]
We would be glad if you can help us out in implementing the feature. We can have the further discussion migrated to our slack - https://slack.metakgp.org

**Comment by proffapt** [comment]
<img width="633" alt="image" src="https://github.com/user-attachments/assets/1dcd8706-d2b2-4b5c-9b35-8e354b56a88d">

Change (reset) password feature exist.

**Comment by proffapt** [comment]
We don't provide support for changing your credentials. 

If you can help us out with the feature implementation, please refer, 
Kindly refer https://github.com/metakgp/naarad-ntfy/issues/2 for more information.
