### ISSUE TITLE
Not able to sign up

### ISSUE THREAD

**Issue by AdityaB-01** [metakgp/naarad#27]
![image](https://github.com/user-attachments/assets/057d21a1-22de-481a-8486-2cca0c2b650d)

what are the possible solutions?

**Comment by proffapt** [comment]
Can you try now?

**Comment by AdityaB-01** [comment]
I tried again after deleting all the cookies and stored data, still the same issue: 

![image](https://github.com/user-attachments/assets/6a57ca2d-aa80-4692-8cb6-d8edfb578994)
![image](https://github.com/user-attachments/assets/077c27f9-0555-4538-8313-ec5500c7e8c4)

**Comment by proffapt** [comment]
Try now.

**Comment by AdityaB-01** [comment]
Yes, thanks for helping. Sign up works but login wont: 

![image](https://github.com/user-attachments/assets/af51d226-3b75-4d37-806f-56c3f7b57ae4)

**Comment by proffapt** [comment]
Understood. Deleting your message as it contains your user token in the attached screenshot.

**Comment by proffapt** [comment]
The issue was resolved, context for future humans.
