### ISSUE TITLE
Removal of gh-pages branch

### ISSUE THREAD

**Issue by athityakumar** [metakgp/naarad#28]
Hey! It seems a bit inconvenient and kind-of-spammy to push 2 commits (due to 2 branches) per commit. github has now introduced an option to decide which branch will contain the website interface. So if we can change that to `master` and store the `index.html` in the root directory rather than at `output/` , then `naarad` can function without `gh-pages` branch,.

This option of changing branches is available in the settings of this repo. But I dont have access to it. 

@hargup : Any suggestion? 
cc @DefCon-007 @vivekiitkgp

**Comment by vivekiitkgp** [comment]
There's actually an even better option. GitHub has added an extra feature where you can keep your site in a special directory called `docs` in the master. GitHub will automatically use content inside this directory to display the website.

So, all one could do is to rename `output` to `docs`.

**Comment by athityakumar** [comment]
@vivekiitkgp : That seems really great, I didn't know about this... So, can we do this (rename `output` to `docs`) and remove `gh-pages` for good?

**Comment by vivekiitkgp** [comment]
The build now occurs from `docs/` dir.
