### ISSUE TITLE
Authorisation mechanism

### ISSUE THREAD

**Issue by proffapt** [metakgp/naarad#3]
### What

Need to think of a way to restrict access based on authorisation. Following are the requirements:
- Should NOT be limited to just KGP Network
- Should use something unique for KGPians

#### Unique KGPian things
- ERP (Can utilise https://github.com/proffapt/iitkgp-erp-login-pypi) to authorise kgpians
- `*@kgpian.iitkgp.ac.in` and `*@iitkgp.ac.in` emails. Can send authorisation link / OTP there

Going ahead with the second option as the most viable. The implementation will be done in [heimdall](https://github.com/metakgp/heimdall/issues/4)

### Why

That's simple, authorisation

### How

Nginx FTW, [this](https://nginx.org/en/docs/http/ngx_http_auth_jwt_module.html) might be helpful, research needs to be done for the correct way but it is doable.

**Comment by Bikram-ghuku** [comment]
Can I work on this?

**Comment by proffapt** [comment]
Done
