### ISSUE TITLE
Make links in post clickable

### ISSUE THREAD

**Issue by hargup** [metakgp/naarad#3]

**Comment by vivekiitkgp** [comment]
Slightly ambiguous. Do you handle the links contained in the posts or the links to the posts? I think you mean the former.

**Comment by hargup** [comment]
> Slightly ambiguous

Changed the title. As of now the links in posts are not click-able.

**Comment by hargup** [comment]
We can use [CommonRegex](https://github.com/madisonmay/CommonRegex) package to recognize links in a text and then replace it with a href. BTW `CommonRegex` package is pretty cool and we can also use it detect time and venue in case of events.

**Comment by vivekiitkgp** [comment]
Coool!

--
https://vivekiitkgp.github.io

**Comment by athityakumar** [comment]
@hargup @vivekiitkgp : the issue I raised was a bit different I guess. For that, can we do something much simpler? Like, a `phrases = string.split(post["message"]," ")` and then check if for any i, `len(phrase[i]) > 20 or 25`. Then remove them post["message"] and append them to a new field post["long_text"] where it is meaningul here in our case that post["long_text"] elements will be hyperlinks. 

That way , mobile view is way better than present scenario. :smile:

**Comment by vivekiitkgp** [comment]
@athityakumar If you have a really long link, then truncate it to something like `docs.google.com/...` This should be sufficient and less work.

**Comment by athityakumar** [comment]
@vivekiitkgp : Say, this is the link to the recruitment Google form of a society - then by truncating it, isn't the purpose of that post lost?

**Comment by vivekiitkgp** [comment]
On Mon, Aug 22, 2016 at 2:06 AM, Athitya Kumar <notifications@github.com>
wrote:

> isn't the purpose of that post lost?


Probably not. Almost always there'll be an accompanying text to clarify the
purpose of the link. If there isn't then even having the full link isn't
going to make it clear. However, if you really feel that it's a critical
feature, I'm not stopping you ;)

--
https://vivekiitkgp.github.io

**Comment by athityakumar** [comment]
@vivekiitkgp : I mean, , even if there's accompanying text to convey the message "we are recruiting" (say) and then we truncate it (the long link) resulting in not being able to open that link, then wouldn't the user be forced to click the "view the post on facebook" to get the link? I was just trying to avoid that... :smile:

**Comment by vivekiitkgp** [comment]
But I don't understand, why won't you be able to open the link? I think
there's some confusion. I mean this -

<a href="<https://docs.google.com/..... [full link]>">
https://docs.google.com/..</a> The truncated text is just for visibility.
You still link to the original url.

Let me know if I am missing your point.

--
https://vivekiitkgp.github.io

**Comment by athityakumar** [comment]
@vivekiitkgp : Oh ok, I meant the same.

**Comment by DefCon-007** [comment]
@hargup For events we don't need to do anything because we already have a different function to get details of the events.
@athityakumar Shortening the url will be cool.

**Comment by athityakumar** [comment]
I guess this has been solved by PR #33

**Comment by athityakumar** [comment]
Ping @hargup @DefCon-007 : This issue should also be resolved. Links are click able & shortened only during display of static site. On using the search, search results don't have click able / shortened links. So, we have to include the function that shortens URL / gives `href` to links from `frontend.py`, into the `fbscraper.py` and include a field `links = []` in `feed.json`.
