### ISSUE TITLE
Debug Web Push

### ISSUE THREAD

**Issue by proffapt** [metakgp/naarad#6]
### Why

It is to be enabled so that desktop users can receive notification even if the web app is closed or not running in the background. 

### How

Web Push was enabled in https://github.com/metakgp/naarad/commit/be3fd95697e025d2def470d98735d5de20e39d60.
- I had to enable it using envs because those keys were sensitive.
- Following option occured which means that envs method should work as this option wouldn't have appeared if this method wasn't correct (env) 
   <img width="880" alt="image" src="https://github.com/metakgp/naarad/assets/86282911/8ae3a921-3514-4718-a062-61ef7e98fe59">
- I also went to server and edited server.yml manually with these values, still same issues

### Issue

Not receiving notification:
- when naarad is open
- when naarad is closed
- And when I go and disable it, all the pending notifications arrive lmfao

**Comment by dhanvithnayak** [comment]
Assign pls :)

**Comment by proffapt** [comment]
@BAGUVIX456 updates?

**Comment by dhanvithnayak** [comment]
Haven't really started working on it, was a little busy. I'll start tomorrow

**Comment by proffapt** [comment]
private and public keys were reversed in the env :)

Thanks to @BAGUVIX456 figuring this out somehow 👀
