### ISSUE TITLE
Auth loop when integrating with heimdall

### ISSUE THREAD

**Issue by proffapt** [metakgp/naarad#8]
refer https://github.com/metakgp/naarad/blob/main/metaploy/naarad.metaploy.conf

**Comment by dhanvithnayak** [comment]
Can you tell me what is to be done here?

**Comment by proffapt** [comment]
Try opening naarad.metaKGP.org/web on firefox and authenticate with heimdall. Then see the behaviour and report here.

**Comment by proffapt** [comment]
Fixed in https://github.com/metakgp/naarad/commit/1da1dd179f8cfac2f9991c90dd7c0de480c56754
