### ISSUE TITLE
Implement a user registration page

### ISSUE THREAD

**Issue by proffapt** [metakgp/naarad#9]
So here's the master stroke:

- User visits a certain endpoint
- A check runs whether the user is existing in the db or not
- If not then register the user and send auto-generated credentials to their kgpian mail
- If registered then redirect them to web app

> [!Note]
> Utilise the `https://heimdall-api.metakgp.org/validate-jwt` endpoint (don't forget to provide the heimdall cookie) to get the kgpian mail

### Generating credentials
- You can get the kgpian mail from the validate-jwt endpoint and the username will be the part before `@kgpian.iitkgp.ac.in`
- Password shall be generated by us and sent over the same mail

### Frontend related
The frontend will be very simple
- If the user is registered, then show that they are registered and ask them to check their mail
- If the user is not registered, then show that they have been registered and check the mail
- In both cases redirect to the webapp after 3 seconds

**Comment by Bikram-ghuku** [comment]
Can I work on this issue?

**Comment by proffapt** [comment]
Sure, go ahead. 
cc: @chirag-ghosh @rohan-b-84

**Comment by chirag-ghosh** [comment]
Which languages are you planning to use @Bikram-ghuku ?

**Comment by Bikram-ghuku** [comment]
Golang for backend

Solidjs for frontend
